### ISSUE TITLE
35 provinsi?

### ISSUE THREAD

**Issue by ddikodroid** [renomureza/cuaca-gempa-rest-api#1]

**Comment by renomureza** [comment]
Ya, apakah ada yang keliru? 

Sumber: https://data.bmkg.go.id/prakiraan-cuaca/

**Comment by ddikodroid** [comment]
> Ya, apakah ada yang keliru?
> 
> Sumber: https://data.bmkg.go.id/prakiraan-cuaca/

itu yg terakhir bukan termasuk provinsi😅

**Comment by renomureza** [comment]
Saya lihat "Provinsi Indonesia" nyediain data cuaca ibu kota setiap provinsi. Keliru di deskripsi harusnya 34, nanti saya perbaiki atau boleh PR.
